# Web3 投资收益工具集 - GitHub Pages 配置

title: "Web3 投资收益工具集"
description: "专业的Web3投资分析工具集合，帮助您在加密货币市场中做出明智的投资决策"
url: "https://scdotbox.github.io"
baseurl: "/crypto_values"

# 作者信息
author:
  name: "Major"
  email: "major@example.com"

# 网站设置
lang: zh-CN
timezone: Asia/Shanghai

# GitHub信息
github:
  repository_url: "https://github.com/scdotbox/crypto_values"
  repository_name: "crypto_values"

# SEO设置
plugins:
  - jekyll-sitemap
  - jekyll-feed

# 排除文件
exclude:
  - README.md
  - deploy.sh
  - .github/
  - .git/ 